"""
Coder Agent：代码生成与审查
核心能力：根据 Architect 的设计约束生成生产级代码，包含单元测试
"""

from typing import Dict, Any, List
from src.agents.base_agent import BaseAgent


class CoderAgent(BaseAgent):
    """
    职责：
    1. 根据架构设计生成服务代码（Python/FastAPI/Go 等）
    2. 实现 Architect 定义的接口契约
    3. 生成分布式锁、缓存、消息队列的集成代码
    4. 自动编写单元测试（pytest）
    5. 代码风格检查（Black/Flake8）
    """

    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        previous = input_data.get("previous_artifacts", {})
        architect_output = previous.get("architecture", {})
        feedback = previous.get("coding_feedback", [])

        services = architect_output.get("architecture", {}).get("services", [])

        generated_code = {}
        tests = {}

        for svc in services:
            # 生成服务代码
            code = self._generate_service_code(svc, architect_output, feedback)
            generated_code[svc["name"]] = code

            # 生成对应测试
            tests[svc["name"]] = self._generate_tests(svc, code)

        return {
            "summary": f"Generated code for {len(services)} services with tests",
            "confidence": 0.85,
            "code": generated_code,
            "tests": tests,
            "lint_results": self._run_linter(generated_code),
            "lines_of_code": sum(len(c.split("\n")) for c in generated_code.values()),
        }

    def _generate_service_code(self, service: Dict, architecture: Dict, feedback: List) -> str:
        """生成单个服务的代码"""
        svc_name = service["name"]

        # 根据反馈调整代码（质量回溯）
        retry_hint = ""
        if feedback:
            retry_hint = f"\n# 修复上一轮测试失败: {feedback[0] if feedback else 'N/A'}\n"

        code = f'''"""
{svc_name} Service
Auto-generated by AutoDevOps Coder Agent
"""

from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional, List
import redis
import json
import logging

logger = logging.getLogger(__name__)
app = FastAPI(title="{svc_name}")

# 配置
REDIS_URL = "redis://localhost:6379/0"
redis_client = redis.from_url(REDIS_URL, decode_responses=True)

# 数据模型
class {svc_name.replace("服务", "")}Create(BaseModel):
    """创建请求模型"""
    name: str
    description: Optional[str] = None

class {svc_name.replace("服务", "")}Response(BaseModel):
    """响应模型"""
    id: str
    name: str
    status: str
    created_at: str

{retry_hint}

@app.post("/api/v1/{svc_name.lower().replace('服务', '')}", response_model={svc_name.replace("服务", "")}Response)
async def create_item(item: {svc_name.replace("服务", "")}Create):
    """
    创建资源
    - 写入数据库
    - 更新缓存
    - 发送事件到消息队列
    """
    try:
        # 生成唯一 ID
        item_id = generate_uuid()

        # 缓存预热
        cache_key = f"{{svc_name.lower()}}:{{item_id}}"
        redis_client.setex(cache_key, 3600, json.dumps(item.dict()))

        # 持久化（实际应调用 Repository 层）
        logger.info(f"Created {{svc_name}} with id {{item_id}}")

        return {svc_name.replace("服务", "")}Response(
            id=item_id,
            name=item.name,
            status="active",
            created_at=datetime.utcnow().isoformat()
        )
    except Exception as e:
        logger.error(f"Failed to create {{svc_name}}: {{str(e)}}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.get("/api/v1/{svc_name.lower().replace('服务', '')}/health")
async def health_check():
    """健康检查端点"""
    return {{"status": "healthy", "service": "{svc_name}"}}

def generate_uuid() -> str:
    import uuid
    return str(uuid.uuid4())

from datetime import datetime
'''
        return code

    def _generate_tests(self, service: Dict, code: str) -> str:
        """生成 pytest 测试代码"""
        svc_name = service["name"].replace("服务", "")
        return f'''"""
Tests for {svc_name} Service
"""

import pytest
from fastapi.testclient import TestClient
from {svc_name.lower()}_service import app

client = TestClient(app)

def test_create_item():
    """测试创建资源"""
    response = client.post("/api/v1/{svc_name.lower()}", json={{
        "name": "Test Item",
        "description": "Test Description"
    }})
    assert response.status_code == 200
    data = response.json()
    assert data["name"] == "Test Item"
    assert data["status"] == "active"
    assert "id" in data

def test_health_check():
    """测试健康检查"""
    response = client.get("/api/v1/{svc_name.lower()}/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"

def test_create_item_validation_error():
    """测试参数校验"""
    response = client.post("/api/v1/{svc_name.lower()}", json={{"invalid_field": "test"}})
    assert response.status_code == 422
'''

    def _run_linter(self, code_dict: Dict[str, str]) -> Dict[str, Any]:
        """模拟代码风格检查"""
        return {
            "style_issues": 0,
            "type_hints_coverage": 0.95,
            "docstring_coverage": 1.0,
            "status": "passed"
        }